sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.8"
  - "2.0.x"
  - "2.1.x"
  - "2.2.x"
  - "2.3.x"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
notifications:
  email:
    - snowyu.lee@gmail.com

